# Generated by Django 4.2.7 on 2025-12-03 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('search', 'Search'), ('buy', 'Buy'), ('sell', 'Sell'), ('transfer', 'Transfer'), ('profit', 'Profit')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bot_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bot_state',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('arbitrage', 'Arbitrage'), ('margin', 'Margin'), ('spot', 'Spot')], max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('exchanges', models.JSONField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSymbolSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=30)),
                ('exchange_1', models.CharField(max_length=50)),
                ('exchange_2', models.CharField(max_length=50)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('open_spread', models.FloatField(default=0.0)),
                ('close_spread', models.FloatField(default=0.0)),
                ('order_size', models.FloatField(default=0.0)),
                ('order_size_usdt', models.FloatField(default=0.0)),
                ('max_orders', models.IntegerField(default=0)),
                ('force_stop', models.BooleanField(default=False)),
                ('total_stop', models.BooleanField(default=False)),
                ('open_ticks', models.IntegerField(default=0)),
                ('close_ticks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_symbol_settings',
            },
        ),
    ]
