# Generated by Django 4.2.7 on 2025-12-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymbolsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botlog',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='trading.trade'),
        ),
        migrations.AddField(
            model_name='botlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersymbolsettings',
            index=models.Index(fields=['user', 'symbol'], name='user_symbol_user_id_6d737f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersymbolsettings',
            unique_together={('user', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'status'], name='trades_user_id_775926_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'opened_at'], name='trades_user_id_57d246_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol'], name='trades_symbol_bf741e_idx'),
        ),
        migrations.AddIndex(
            model_name='botstate',
            index=models.Index(fields=['user', 'symbol'], name='bot_state_user_id_105de8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='botstate',
            unique_together={('user', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['user', 'created_at'], name='bot_logs_user_id_1793e0_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['log_type'], name='bot_logs_log_typ_0bbcdc_idx'),
        ),
    ]
