# Generated by Django 4.2.7 on 2025-12-03 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange_id', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('free_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.CreateModel(
            name='ExchangeConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange_id', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('gateio', 'Gate.io'), ('mexc', 'MEXC'), ('bingx', 'BingX'), ('bitget', 'Bitget')], max_length=20)),
                ('api_key_encrypted', models.TextField()),
                ('secret_key_encrypted', models.TextField()),
                ('passphrase_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_connections',
            },
        ),
    ]
