# Generated by Django 4.2.7 on 2025-12-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exchangeconnection',
            index=models.Index(fields=['user', 'exchange_id'], name='exchange_co_user_id_a61eba_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeconnection',
            index=models.Index(fields=['user', 'is_active'], name='exchange_co_user_id_a2daf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeconnection',
            unique_together={('user', 'exchange_id')},
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['user', 'exchange_id'], name='balances_user_id_a5500a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('user', 'exchange_id', 'currency')},
        ),
    ]
