# Generated by Django 4.2.7 on 2025-12-03 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PnLHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pnl_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cumulative_pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('trades_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pnl_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
