# Generated by Django 4.2.7 on 2025-12-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnlhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pnlhistory',
            index=models.Index(fields=['user', 'timestamp'], name='pnl_history_user_id_b7ffef_idx'),
        ),
    ]
